namespace: "namespace_name"
name: "collection_name"
version: "1.0.0"
readme: "README.md"
authors:
    - K Ram Sai
    - "Author2 (https://author2.example.com)"
    - "Author3 <author3@example.com>"
dependencies: []
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "https://github.com/KRams2019/Ansible"
